In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("heart.csv")

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
df.columns = ['age', 'sex', 'chest_pain_type', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar', 'rest_ecg', 'max_heart_rate_achieved',
       'exercise_induced_angina', 'st_depression', 'st_slope', 'num_major_vessels', 'thalassemia', 'target']

In [5]:
df.head(10)

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0   63    1                3                     145          233   
1   37    1                2                     130          250   
2   41    0                1                     130          204   
3   56    1                1                     120          236   
4   57    0                0                     120          354   
5   57    1                0                     140          192   
6   56    0                1                     140          294   
7   44    1                1                     120          263   
8   52    1                2                     172          199   
9   57    1                2                     150          168   

   fasting_blood_sugar  rest_ecg  max_heart_rate_achieved  \
0                    1         0                      150   
1                    0         1                      187   
2                    0         0                      172   
3                    0         1                      178   
4                    0         1                      163   
5                    0         1                      148   
6                    0         0                      153   
7                    0         1                      173   
8                    1         1                      162   
9                    0         1                      174   

   exercise_induced_angina  st_depression  st_slope  num_major_vessels  \
0                        0            2.3         0                  0   
1                        0            3.5         0                  0   
2                        0            1.4         2                  0   
3                        0            0.8         2                  0   
4                        1            0.6         2                  0   
5                        0            0.4         1                  0   
6                        0            1.3         1                  0   
7                        0            0.0         2                  0   
8                        0            0.5         2                  0   
9                        0            1.6         2                  0   

   thalassemia  target  
0            1       1  
1            2       1  
2            2       1  
3            2       1  
4            2       1  
5            1       1  
6            2       1  
7            3       1  
8            3       1  
9            2       1

In [6]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
rest_ecg                   0
max_heart_rate_achieved    0
exercise_induced_angina    0
st_depression              0
st_slope                   0
num_major_vessels          0
thalassemia                0
target                     0
dtype: int64

In [7]:
#no missing data

In [9]:
#Splitting data into training and test sets.

In [10]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [12]:
#Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [14]:
X_train=sc.fit_transform(X_train)

In [15]:
X_test=sc.fit_transform(X_test)

In [16]:
X_train

array([[ 0.35256528,  0.70243936,  0.9870291 , ...,  0.96222601,
         1.22723311,  1.12135917],
       [-0.31068598,  0.70243936, -0.91982712, ...,  0.96222601,
         0.25993479, -0.45968761],
       [-0.08960223,  0.70243936,  0.9870291 , ...,  0.96222601,
        -0.70736353,  1.12135917],
       ...,
       [ 0.13148153,  0.70243936,  1.94045721, ..., -0.6557392 ,
        -0.70736353,  1.12135917],
       [-0.86339537,  0.70243936,  0.9870291 , ...,  0.96222601,
        -0.70736353, -0.45968761],
       [ 0.35256528,  0.70243936,  0.03360099, ..., -0.6557392 ,
        -0.70736353, -0.45968761]])

In [17]:
X_test

array([[ 1.88467414e+00,  6.17914381e-01, -1.00073126e+00,
         7.34146768e-01, -1.58011928e+00, -3.89249472e-01,
         9.23936435e-01, -1.17273867e+00,  1.61834719e+00,
         1.85739818e+00, -2.27884246e+00, -7.37408534e-01,
         1.15114507e+00],
       [ 1.21794690e+00,  6.17914381e-01,  2.08260290e+00,
         2.09766471e+00, -3.50459223e-01, -3.89249472e-01,
        -1.08232554e+00,  2.19163552e-01, -6.17914381e-01,
        -2.20044964e-01, -6.29394583e-01, -7.37408534e-01,
         1.15114507e+00],
       [ 6.62340871e-01,  6.17914381e-01,  2.08260290e+00,
         2.09766471e+00,  1.06480990e+00, -3.89249472e-01,
        -1.08232554e+00,  4.04750515e-01, -6.17914381e-01,
        -6.35533593e-01, -6.29394583e-01, -7.37408534e-01,
         1.15114507e+00],
       [ 7.73462077e-01,  6.17914381e-01, -1.00073126e+00,
        -3.56667589e-01,  3.68775907e-01, -3.89249472e-01,
        -1.08232554e+00, -4.30390820e-01,  1.61834719e+00,
         2.06514249e+00, -6.29394583e

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[25  8]
 [ 4 39]]


0.8421052631578947

In [23]:
#using decision tree classification

In [24]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [25]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]]


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[24  9]
 [ 9 34]]


0.7631578947368421

# Efficiency reduced.

In [27]:
#using naive bayes

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [29]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7894736842105263

In [30]:
#using kernel svm

In [31]:
from sklearn.svm import SVC

In [34]:
svm=SVC()
svm.fit(X_train,y_train)

SVC()

In [35]:
y_pred = svm.predict(X_test)
accuracy_score(y_test, y_pred)

0.8552631578947368

# Using SVM efficiency improved a bit-85.826%

In [36]:
#using SVM

In [37]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [38]:
y_pred = classifier.predict(X_test)

In [39]:
accuracy_score(y_test, y_pred)

0.8289473684210527

In [40]:
#using KNN

In [41]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
KNN=KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None)

In [45]:
KNN.fit(X_train,y_train)

KNeighborsClassifier()

In [46]:
y_pred = KNN.predict(X_test)

In [47]:
accuracy_score(y_test, y_pred)

0.868421052631579

# KNN gives best efficiency till now of 86.84%

In [48]:
#using xg_boost classifier

In [49]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[25  8]
 [ 8 35]]


0.7894736842105263